### ISSUE TITLE
[Question] Why `{}.hasOwnProperty()`?

### ISSUE THREAD

**Issue by h-h-h-h** [rogerpoon/stringset#1]
Why is it *first* instead of *second*?

```diff
 var obj = {};
 
 bool contains(string value) {
-    return {}.hasOwnProperty.call(this.obj, value);
+    return this.obj.hasOwnProperty(value);
 }
```

**Comment by rogerpoon** [comment]
Semantically, they are the same.

Internally, the JS++ compiler does generate code this way (e.g. on `foreach` loops) to avoid unnecessary runtime symbol table lookups. See my answer here: https://stackoverflow.com/a/7375418/938559

However, in this particular case, I don't think it makes a difference. You're welcome to introduce the change if there's a statistically-significant difference in benchmark results.

**Comment by h-h-h-h** [comment]
Ah, I see. That's interesting.

Thanks for the explanation.
